# Generated by Django 4.2.14 on 2024-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=15)),
                ('load_applied', models.IntegerField(blank=True, null=True)),
                ('date_of_application', models.DateField(blank=True, editable=False, null=True)),
                ('date_of_approval', models.DateField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Connection Released', 'Connection Released'), ('Rejected', 'Rejected')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ownership', models.CharField(choices=[('JOINT', 'JOINT'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_id_type', models.CharField(choices=[('AADHAR', 'AADHAR'), ('PAN', 'PAN'), ('PASSPORT', 'PASSPORT'), ('VOTER_ID', 'VOTER_ID')], editable=False, max_length=10)),
                ('id_number', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_id', to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='backend.user'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('Other', 'Other')], max_length=10)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='backend.user')),
            ],
        ),
    ]
